### ISSUE TITLE
Quiz Generate Validation

### ISSUE THREAD

**Issue by mikhailocampo** [radicalxdev/kai-ai-backend#30]
```python
def validate_response(self, response: Dict) -> bool:
        try:
            # Assuming the response is already a dictionary
            if isinstance(response, dict):
                if 'question' in response and 'choices' in response and 'answer' in response and 'explanation' in response:
                    choices = response['choices']
                    if isinstance(choices, dict):
                        for key, value in choices.items():
                            if not isinstance(key, str) or not isinstance(value, str):
                                return False
                        return True
            return False
        except TypeError as e:
            if self.verbose:
                logger.error(f"TypeError during response validation: {e}")
            return False

    def format_choices(self, choices: Dict[str, str]) -> List[Dict[str, str]]:
        return [{"key": k, "value": v} for k, v in choices.items()]
```

![image](https://github.com/radicalxdev/kai-ai-backend/assets/139303992/5cbc7b57-3ea8-4c84-8508-fcd7c9ef7257)
The above error comes from the `validate_response` in which we are destructuring the response from the model. We need a way to remove the backticks JSON and then continue with the rest of the validation as normal

**Comment by AaronSosaRamos** [comment]
Please, can you specify more the WARNING - Invalid response format? Because it is not always the backticks. 
![image](https://github.com/radicalxdev/kai-ai-backend/assets/113047749/ac0e2dcd-9fc4-42fb-8907-69246fc20844)

**Comment by mikhailocampo** [comment]
![image](https://github.com/radicalxdev/kai-ai-backend/assets/139303992/73d1b9fc-08f7-4ffd-bdd3-5093312b2f4d)

**Comment by AaronSosaRamos** [comment]
@mikhailocampo It works normally in my local environment:
![image](https://github.com/radicalxdev/kai-ai-backend/assets/113047749/20c30b1d-29d6-42e5-b3c2-6082495289c3)
![image](https://github.com/radicalxdev/kai-ai-backend/assets/113047749/36e39451-3ec4-4b3a-a1b0-f81330ac2f5e)

**Comment by AaronSosaRamos** [comment]
@mikhailocampo Have you cloned PR #31 with the last commits?
